#define CONFIG_DEVICE_NAME       "Garage Door Duo"
#define CONFIG_AP_NAME            CONFIG_DEVICE_NAME
#define CONFIG_DEVICE_NAME_1     "Door one"
#define CONFIG_DEVICE_NAME_2     "Door two"
#define CONFIG_RELAY_1            D6
#define CONFIG_RELAY_2            D7
#define CONFIG_RELAY_ON           LOW
#define CONFIG_SENSOR_1           D1
#define CONFIG_SENSOR_2           D2
#define RELAY_PULSE               500
#define CONFIG_MANUFACTURER      "William Giles (wmgx.io)"
#define CONFIG_SERIAL_NUMBER     "*****"
#define CONFIG_FIRMWARE          "1.3"
#define CONGIG_MODEL             "Garage Door Controler Pro Duo"
#define CONFIG_HOMEKIT_PASSWORD  "111-11-111"
#define CONFIG_HOMEKIT_SETUP_ID  "ID44"

// homekit stuff
#define HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_OPEN      0
#define HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_CLOSED    1
#define HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_OPENING   2
#define HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_CLOSING   3
#define HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_STOPPED   4
#define HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_UNKNOWN   255

#define HOMEKIT_CHARACTERISTIC_TARGET_DOOR_STATE_OPEN       0
#define HOMEKIT_CHARACTERISTIC_TARGET_DOOR_STATE_CLOSED     1
#define HOMEKIT_CHARACTERISTIC_TARGET_DOOR_STATE_UNKNOWN    255
