#define CONFIG_DEVICE_NAME       "Garage Door"
#define CONFIG_AP_NAME            CONFIG_DEVICE_NAME
#define CONFIG_RELAY              NULL
#define CONFIG_SW                 3
#define CONFIG_MANUFACTURER      "William Giles (wmgx.io)"
#define CONFIG_SERIAL_NUMBER     "*****"
#define CONFIG_FIRMWARE          "0.1"
#define CONGIG_MODEL             "Garage Door Controler Pro"
#define CONFIG_HOMEKIT_PASSWORD  "111-11-111"
#define CONFIG_HOMEKIT_SETUP_ID  "ID44"

// homkit stuff
#define HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_OPEN      0
#define HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_CLOSED    1
#define HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_OPENING   2
#define HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_CLOSING   3
#define HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_STOPPED   4
#define HOMEKIT_CHARACTERISTIC_CURRENT_DOOR_STATE_UNKNOWN   255

#define HOMEKIT_CHARACTERISTIC_TARGET_DOOR_STATE_OPEN       0
#define HOMEKIT_CHARACTERISTIC_TARGET_DOOR_STATE_CLOSED     1
#define HOMEKIT_CHARACTERISTIC_TARGET_DOOR_STATE_UNKNOWN    255
